### ISSUE TITLE
Grid displaying

### ISSUE THREAD

**Issue by aboozaid** [ganapativs/react-delightful-scroller#35]
Currently, I have an issue which is items always display under each other. Could you show me a better way to do this in the library.

![Screen Shot 2020-06-18 at 7 50 08 PM](https://user-images.githubusercontent.com/30879096/85055054-455e2100-b19d-11ea-976c-db9c36e176a7.png)

Thank you.

**Comment by aboozaid** [comment]
@ganapativs wish you have an answer. I notice that the lib always put a parent div without any styles as well as a child div for every batch.

**Comment by ganapativs** [comment]
Can you share a demo? may be in codesanbox? What is the layout you are trying to achieve?
